FROM ubuntu:16.04
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

### Environment variables
ENV DEBIAN_FRONTEND='noninteractive' \
    HOME='/config' 


### Install Applications DEBIAN_FRONTEND=noninteractive  --no-install-recommends
RUN apt-get update && \
    apt-get -y --no-install-recommends dist-upgrade && \
    apt-get install -y --no-install-recommends ca-certificates apt-transport-https avahi-daemon dbus libnss-mdns  && \
    apt-get install -y --no-install-recommends curl gcc make git libc-dev && \
    git clone --depth 1 https://github.com/ncopa/su-exec /tmp/su-exec && \
    cd /tmp/su-exec && \
    make && \
    cp /tmp/su-exec/su-exec /usr/local/bin/su-exec && \
    echo deb https://downloads.plex.tv/repo/deb ./public main | tee /etc/apt/sources.list.d/my-plexmediaserver.list && \
    curl -o /tmp/PlexSign.key https://downloads.plex.tv/plex-keys/PlexSign.key && \
    apt-key add /tmp/PlexSign.key && \
    apt-get update && \
    apt-get install -y --no-install-recommends plexmediaserver && \
    apt-get purge -y --auto-remove curl gcc make git libc-dev && \
    apt-get -y autoclean && \
    apt-get -y clean && \
    apt-get -y autoremove && \
    rm -rf /tmp/* && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/tmp/*

### Volume
VOLUME ["/config", "/transcode", "/tv", "/movies", "/animes", "/music"]

### Expose ports
EXPOSE 32400 
EXPOSE 32400/udp 
EXPOSE 32469
EXPOSE 32469/udp 
EXPOSE 5353/udp 
EXPOSE 1900/udp

### Running User: not used, managed by docker-entrypoint.sh
#USER plex

### Start Plex
COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["plex"]
