FROM digrouz/debian-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

### Environment variables
ENV DEBIAN_FRONTEND='noninteractive' \
    TERM='xterm' \
    APPUSER='plex' \
    APPUID='10011' \
    APPGID='10011' \
    PLEX_MEDIA_SERVER_INFO_DEVICE='docker' \
    PLEXVERSION='1.32.5.7516' \
    PLEXHASH='8f4248874' \
    NVIDIA_DRIVER_CAPABILITIES='compute,video,utility'

# Copy config files
COPY root/ /

### Install Applications DEBIAN_FRONTEND=noninteractive  --no-install-recommends
RUN set -x && \
    apt-get update && \
    apt-get -y --no-install-recommends dist-upgrade && \
    apt-get install -y --no-install-recommends\
      ca-certificates \
      apt-transport-https \
      curl \
    && \
    curl -sL https://downloads.plex.tv/plex-media-server-new/${PLEXVERSION}-${PLEXHASH}/debian/plexmediaserver_${PLEXVERSION}-${PLEXHASH}_amd64.deb -o /tmp/plexmediaserver_${PLEXVERSION}-${PLEXHASH}_amd64.deb && \
    echo deb https://downloads.plex.tv/repo/deb public main | tee /etc/apt/sources.list.d/my-plexmediaserver.list && \
    curl https://downloads.plex.tv/plex-keys/PlexSign.key -o /etc/apt/trusted.gpg.d/my-plexmediaserver.asc && \
    apt-get update && \
    dpkg -i --force-confold \
      /tmp/plexmediaserver_${PLEXVERSION}-${PLEXHASH}_amd64.deb \
    && \
    apt-get -y autoclean && \
    apt-get -y clean && \
    apt-get -y autoremove && \
    rm -rf /tmp/* \
           /var/lib/apt/lists/* \
           /var/tmp/*

### Expose ports
EXPOSE 8324/tcp
EXPOSE 32400/tcp
EXPOSE 32410/udp
EXPOSE 32412/udp
EXPOSE 32413/udp
EXPOSE 32414/udp
EXPOSE 32469/tcp
EXPOSE 5353/udp
EXPOSE 1900/udp

### Running User: not used, managed by docker-entrypoint.sh
#USER plex

### Start Plex
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["plex"]
