FROM centos:7
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='plex' \
    APPUID='10011' \
    APPGID='10011' \
    PLEX_MEDIA_SERVER_INFO_DEVICE='docker' \
    PLEXVERSION='1.22.3.4392' \
    PLEXHASH='d7c624def'

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER=${APPUSER} && \
    MYUID=${APPUID} && \
    MYGID=${APPGID} && \
    yum-config-manager --add-repo /tmp/custom.repo && \
    yum install -y epel-release && \
    yum update -y && \
    yum install -y \
      avahi \
      nss-mdns \
      avahi-compat-libdns_sd \
      su-exec \
    && \
    cd /tmp && \
    curl -sL https://downloads.plex.tv/plex-media-server-new/${PLEXVERSION}-${PLEXHASH}/redhat/plexmediaserver-${PLEXVERSION}-${PLEXHASH}.x86_64.rpm -o /tmp/plexmediaserver-${PLEXVERSION}-${PLEXHASH}.x86_64.rpm && \
    COMM=$(cat /proc/1/comm) && \
    echo "systemd" > /proc/1/comm && \
    yum install -y /tmp/plexmediaserver-${PLEXVERSION}-${PLEXHASH}.x86_64.rpm && \
    echo ${COMM} > /proc/1/comm && \
    ConfigureUser && \
    mkdir /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    yum clean all && \
    rm -rf /opt/sickchill/.git* \
           /tmp/* \
           /var/cache/yum/* \
           /var/tmp/*

### Volume
VOLUME ["/transcode", "/tv", "/movies", "/animes", "/music"]

### Expose ports
EXPOSE 3005
EXPOSE 8324
EXPOSE 32400
EXPOSE 32400/udp
EXPOSE 32410/udp
EXPOSE 32412/udp
EXPOSE 32413/udp
EXPOSE 32414/udp
EXPOSE 32469
EXPOSE 32469/udp
EXPOSE 5353/udp
EXPOSE 1900/udp

### Running User: not used, managed by docker-entrypoint.sh
#USER plex

### Start Plex
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["plex"]
