
ARG PLEXVERSION='1.32.5.7349'
ARG PLEXHASH='8f4248874'

FROM rockylinux/rockylinux:8.7 AS su-exec-builder

RUN set -x && \
    dnf update -y && \
    dnf install -y \
      gcc \
      make \
      git \
    && \
    git clone --depth 1 https://github.com/ncopa/su-exec.git /opt/su-exec && \
    cd /opt/su-exec && \
    make

FROM rockylinux/rockylinux:8.7
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG PLEXVERSION
ARG PLEXHASH

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='plex' \
    APPUID='10011' \
    APPGID='10011' \
    PLEX_MEDIA_SERVER_INFO_DEVICE='docker' \
    PLEXVERSION="${PLEXVERSION}" \
    PLEXHASH="${PLEXHASH}"

# Copy config files
COPY root/ /
COPY --from=su-exec-builder /opt/su-exec/su-exec /usr/local/bin/su-exec

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER=${APPUSER} && \
    MYUID=${APPUID} && \
    MYGID=${APPGID} && \
    dnf install -y epel-release && \
    dnf update -y && \
    dnf install -y \
      dnf-plugins-core \
    && \
    dnf config-manager --set-enabled powertools && \
    dnf install -y \
      avahi \
      nss-mdns \
      avahi-compat-libdns_sd \
    && \
    cd /tmp && \
    curl -sL https://downloads.plex.tv/plex-media-server-new/${PLEXVERSION}-${PLEXHASH}/redhat/plexmediaserver-${PLEXVERSION}-${PLEXHASH}.x86_64.rpm -o /tmp/plexmediaserver-${PLEXVERSION}-${PLEXHASH}.x86_64.rpm && \
    COMM=$(cat /proc/1/comm) && \
    echo "systemd" > /proc/1/comm && \
    dnf install -y /tmp/plexmediaserver-${PLEXVERSION}-${PLEXHASH}.x86_64.rpm && \
    echo ${COMM} > /proc/1/comm && \
    ConfigureUser && \
    mkdir /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    dnf clean all && \
    rm -rf /tmp/* \
           /var/cache/yum/* \
           /var/tmp/*

### Volume
VOLUME ["/transcode", "/tv", "/movies", "/animes", "/music"]

### Expose ports
EXPOSE 3005
EXPOSE 8324
EXPOSE 32400
EXPOSE 32400/udp
EXPOSE 32410/udp
EXPOSE 32412/udp
EXPOSE 32413/udp
EXPOSE 32414/udp
EXPOSE 32469
EXPOSE 32469/udp
EXPOSE 5353/udp
EXPOSE 1900/udp

### Running User: not used, managed by docker-entrypoint.sh
#USER plex

### Start Plex
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["plex"]
